/*
 * errorstate.h
 *
 *  Created on: Nov 25, 2022
 *      Author: esraa
 */

#ifndef ERRORSTATE_H_
#define ERRORSTATE_H_

typedef enum
{
	ES_NOK,
	ES_OK,
	ES_NULL_POINTER,
	ES_OUT_OF_RANGE,
	ES_FUNC_IS_BUSY,
	ES_FUNC_IS_IDLE,
	ES_TWI_RESERVED_ADDRESS,
	ES_TWI_START_COND_ERROR,
	ES_TWI_REP_START_COND_ERROR,
	ES_TWI_SLAVE_ADD_WRITE_ERROR,
	ES_TWI_SLAVE_ADD_READ_ERROR,
	ES_TWI_MASTER_WRITE_DATA_BYTE_ERROR,
	ES_TWI_MASTER_READ_DATA_BYTE_ERROR
}ES_t;

#endif /* ERRORSTATE_H_ */
