/*
 * errorStates.h
 *
 *  Created on: Feb 11, 2023
 *      Author: REZK
 */

#ifndef ERRORSTATES_H_
#define ERRORSTATES_H_


typedef enum
{
	ES_OK,
	ES_NOK,
	ES_NULL_POINTER,
	ES_OUT_OF_RANGE,
	ES_FUNC_IS_BUSY,
	ES_FUNC_IS_IDLE,
	ES_TWI_RESERVED_ADDRESS,
	ES_TWI_START_COND_ERROR,
	ES_TWI_REP_START_COND_ERROR,
	ES_TWI_SLAVE_ADD_WRITE_ERROR,
	ES_TWI_SLAVE_ADD_READ_ERROR,
	ES_TWI_MASTER_WRITE_DATA_BYTE_ERROR,
	ES_TWI_MASTER_READ_DATA_BYTE_ERROR

}ES_t;




#endif /* ERRORSTATES_H_ */
